name: faraos_ruleta
description: "Ruleta de premios - FAROS"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # Ruleta
  flutter_fortune_wheel: ^1.3.0

  # Utilidades
  intl: ^0.19.0
  file_selector: ^1.0.3
  confetti: ^0.7.0
  url_launcher: ^6.3.0

  # Íconos
  font_awesome_flutter: ^10.7.0

  # QR para el paso de “seguir red”
  qr_flutter: ^4.1.0

  # Íconos estilo iOS (opcional)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_faros.png
    - assets/logo_apasep.png
